import type { Metadata } from "next";
import localFont from "next/font/local";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar";
import InfoOverlayShell from "./components/InfoOverlayShell";
import { LanguageProvider } from "./contexts/LanguageContext";

const romRegular = localFont({
  src: "../public/ABCROM-Regular-Trial.woff2",
  variable: "--font-romRegular",
  display: "swap",
});

const romRegularItalic = localFont({
  src: "../public/ABCROM-RegularItalic-Trial.woff2",
  variable: "--font-romRegularItalic",
  display: "swap",
});

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-notoSansJP",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/yakuhanjp@4.1.1/dist/css/yakuhanjp.css" />
      </head>
      <body className={`${romRegular.variable} ${romRegularItalic.variable} ${notoSansJP.variable} antialiased`}>
        <div className="page-grid-background" aria-hidden="true" />
        <div className="nav-scroll-blur" aria-hidden="true" />
        <LanguageProvider>
          <Navbar />
          {children}
          <InfoOverlayShell />
        </LanguageProvider>
      </body>
    </html>
  );
}
