import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Navbar from "./components/Navbar";

const romRegular = localFont({
  src: "../public/ABCROM-Regular-Trial.woff2",
  variable: "--font-romRegular",
  display: "swap",
});

const romRegularItalic = localFont({
  src: "../public/ABCROM-RegularItalic-Trial.woff2",
  variable: "--font-romRegularItalic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${romRegular.variable} ${romRegularItalic.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
